### ISSUE TITLE
关于系列教程

### ISSUE THREAD

**Issue by heycmm** [ellermister/mybili#1]
首先，这个太好用了！

能否支持全部收藏夹，按名称下载。

能否再支持收藏的系列，如教程类的连续下载？

**Comment by ellermister** [comment]
会下载你的所有收藏夹中的所有视频。
不会下载剧集/播放列表， 情况比较复杂，有一些歌单只收藏一首歌，全量下非常大。一般情况下剧集大部分都存在第三方资源，而非个人博主原创，所以下载意义不大，没有纳入。

下载通过的是 `yt-dlp` 这个程序，它默认支持剧集播放列表下载，你有需求可以查看他的文档。

**Comment by youppos** [comment]
出现如下报错，拉取不了镜像，如何解决
/
root@node-01 /mnt/user/mybili]# docker-compose up -d
[+] Running 2/2
 ✘ mybili Error                                                                                               16.3s 
 ✘ redis Error                                                                                                16.3s 
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[root@node-01 /mnt/user/mybili]# curl https://registry-1.docker.io/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}

**Comment by heycmm** [comment]
确实，我再研究下。

> 会下载你的所有收藏夹中的所有视频。 不会下载剧集/播放列表， 情况比较复杂，有一些歌单只收藏一首歌，全量下非常大。一般情况下剧集大部分都存在第三方资源，而非个人博主原创，所以下载意义不大，没有纳入。
> 
> 下载通过的是 `yt-dlp` 这个程序，它默认支持剧集播放列表下载，你有需求可以查看他的文档。
确实，我去研究下。
