### ISSUE TITLE
RedisException Connection refused

### ISSUE THREAD

**Issue by ZeroBlock0** [ellermister/mybili#13]
![image](https://github.com/user-attachments/assets/6660f6f6-37dc-409a-a14f-9166509acd2b)
这个是怎么回事，打不开

**Comment by ZeroBlock0** [comment]
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:1CJOuWliDyx0ZBIZyn0gRKOOOq6+23YG/UHcUP4ffaU=
APP_DEBUG=true
APP_TIMEZONE=UTC
APP_URL=http://localhost

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file
# APP_MAINTENANCE_STORE=database

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=sqlite
# DB_HOST=127.0.0.1
# DB_PORT=3306
# DB_DATABASE=laravel
# DB_USERNAME=root
# DB_PASSWORD=

SESSION_DRIVER=redis
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=redis

CACHE_STORE=redis
CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379
REDIS_DB=3
REDIS_PREFIX=

MAIL_MAILER=log
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"

**Comment by ZeroBlock0** [comment]
> APP_NAME=LaravelAPP_NAME=拉拉维尔 APP_ENV=localAPP_ENV=本地 APP_KEY=base64:1CJOuWliDyx0ZBIZyn0gRKOOOq6+23YG/UHcUP4ffaU=APP_KEY=base64：1CJOuWliDyx0ZBIZyn0gRKOOOq6+23YG/UHcUP4ffaU= APP_DEBUG=trueAPP_DEBUG=true APP_TIMEZONE=UTCAPP_TIMEZONE=UTC APP_URL=APP_URL=[http://localhosthttp://localhost](http://localhost)
> 
> APP_LOCALE=enAPP_LOCALE=en APP_FALLBACK_LOCALE=enAPP_FALLBACK_LOCALE=en APP_FAKER_LOCALE=en_USAPP_FAKER_LOCALE=en_US
> 
> APP_MAINTENANCE_DRIVER=fileAPP_MAINTENANCE_DRIVER=文件
> 
> # APP_MAINTENANCE_STORE=database
> APP_MAINTENANCE_STORE=数据库
> BCRYPT_ROUNDS=12BCRYPT_ROUNDS=12
> 
> LOG_CHANNEL=stackLOG_CHANNEL=堆栈 LOG_STACK=singleLOG_STACK=single LOG_DEPRECATIONS_CHANNEL=nullLOG_DEPRECATIONS_CHANNEL=空 LOG_LEVEL=debugLOG_LEVEL=调试
> 
> DB_CONNECTION=sqliteDB_CONNECTION=sqlite
> 
> # DB_HOST=127.0.0.1
> DB_HOST=127.0.0.1
> # DB_PORT=3306DB_PORT=3306
> # DB_DATABASE=laravel
> DB_DATABASE=拉拉韦尔
> # DB_USERNAME=root
> DB_USERNAME=根
> # DB_PASSWORD=DB_PASSWORD=
> SESSION_DRIVER=redisSESSION_DRIVER=redis SESSION_LIFETIME=120SESSION_LIFETIME=120 SESSION_ENCRYPT=falseSESSION_ENCRYPT=假 SESSION_PATH=/SESSION_PATH=/ SESSION_DOMAIN=nullSESSION_DOMAIN=空
> 
> BROADCAST_CONNECTION=logBROADCAST_CONNECTION=日志 FILESYSTEM_DISK=localFILESYSTEM_DISK=本地 QUEUE_CONNECTION=redisQUEUE_CONNECTION=redis
> 
> CACHE_STORE=redisCACHE_STORE=redis CACHE_PREFIX=CACHE_PREFIX=
> 
> MEMCACHED_HOST=127.0.0.1MEMCACHED_HOST=127.0.0.1
> 
> REDIS_CLIENT=phpredis REDIS_HOST=redis REDIS_PASSWORD=null REDIS_PORT=6379 REDIS_DB=3 REDIS_PREFIX=
> 
> MAIL_MAILER=log MAIL_HOST=127.0.0.1 MAIL_PORT=2525 MAIL_USERNAME=null MAIL_PASSWORD=null MAIL_ENCRYPTION=null MAIL_FROM_ADDRESS="[hello@example.com](mailto:hello@example.com)" MAIL_FROM_NAME="${APP_NAME}"
> 
> AWS_ACCESS_KEY_ID= AWS_SECRET_ACCESS_KEY= AWS_DEFAULT_REGION=us-east-1 AWS_BUCKET= AWS_USE_PATH_STYLE_ENDPOINT=false
> 
> VITE_APP_NAME="${APP_NAME}"

这个是env

**Comment by ellermister** [comment]
数据库默认不需要配置，应该是sqlite；
你的标题和截图内容不符，检查下redis是否可以连接

**Comment by ZeroBlock0** [comment]
![image](https://github.com/user-attachments/assets/c9a3f865-51de-4f7e-8aa2-9e8ef2369a1c)

**Comment by ZeroBlock0** [comment]
解决了，重新pull一遍就好了
