### ISSUE TITLE
添加了cookie，并且状态为有效，怎么看不到进度

### ISSUE THREAD

**Issue by ZeroBlock0** [ellermister/mybili#15]
![image](https://github.com/user-attachments/assets/30cdf9be-88c0-414b-981b-2aaceacb32a2)

**Comment by ellermister** [comment]
点右边的查看任务，观察有没有异步任务在执行或者创建了

**Comment by ZeroBlock0** [comment]
![image](https://github.com/user-attachments/assets/4ecf2819-4256-4a0e-b964-5b443d62b0d0)

**Comment by ZeroBlock0** [comment]
可能是太多了，估计还要等一会
