### ISSUE TITLE
成功部署到群晖nas，出现视频有声音没画面

### ISSUE THREAD

**Issue by liuguang927** [ellermister/mybili#19]
程序可以正常运行，有声音，但是大多视频没有画面，极少部分视频可以正常播放。

**Comment by liuguang927** [comment]
> 程序可以正常运行，有声音，但是大多视频没有画面，极少部分视频可以正常播放。

我在本地保存的文件查看了，视频文件是正常的

**Comment by phantasy36** [comment]
> > 程序可以正常运行，有声音，但是大多视频没有画面，极少部分视频可以正常播放。
> 
> 我在本地保存的文件查看了，视频文件是正常的

一样。群晖，有声音没有图像。
