### ISSUE TITLE
我的192.168.31.14:5151页面会出现如图的报错，提示是redis的报错

### ISSUE THREAD

**Issue by summ9919** [ellermister/mybili#7]
我的192.168.31.14:5151页面在运行几个小时之后会出现如图的报错，提示是redis的报错，我在mnt/user/mybili/data文件里有看到下载缓存的视频，然后我尝试重启redis和mybili两个容器，但是还是同样的页面报错，请问这是我的写入没有权限导致的吗？
![微信截图_20240921083147](https://github.com/user-attachments/assets/65b819a7-7df2-4318-9400-a3db0bd6c0a5)
![微信截图_20240921083132](https://github.com/user-attachments/assets/b573c6be-abf0-4218-984f-6b0e94a1c06f)

**Comment by summ9919** [comment]
我发现我如果把我的群晖网关设为旁路由之后就能正常打开了，因为我的旁路由上面有梯子。请问mybili它也会需要墙外环境吗？

**Comment by ellermister** [comment]
不需要外网环境，redis那个警告可能影响无法持久化存储，但应该不影响使用。或者你先搜下这个错误怎么改配置。

**Comment by summ9919** [comment]
好呢，谢谢您的回复

**Comment by summ9919** [comment]
我解决了，原因是redis把所在的磁盘空间占用完了，我扩容之后就没有问题了。
